export enum RegionEnum {
  CARIBBEAN = 'Caribbean',
  SOUTHERN_AND_CENTRAL_ASIA = 'Southern and Central Asia',
  CENTRAL_AFRICA = 'Central Africa',
  SOUTHERN_EUROPE = 'Southern Europe',
  MIDDLE_EAST = 'Middle East',
  SOUTH_AMERICA = 'South America',
  POLYNESIA = 'Polynesia',
  ANTARCTICA = 'Antarctica',
  AUSTRALIA_AND_NEW_ZEALAND = 'Australia and New Zealand',
  WESTERN_EUROPE = 'Western Europe',
  EASTERN_AFRICA = 'Eastern Africa',
  WESTERN_AFRICA = 'Western Africa',
  EASTERN_EUROPE = 'Eastern Europe',
  CENTRAL_AMERICA = 'Central America',
  NORTH_AMERICA = 'North America',
  SOUTHEAST_ASIA = 'Southeast Asia',
  SOUTHERN_AFRICA = 'Southern Africa',
  EASTERN_ASIA = 'Eastern Asia',
  NORDIC_COUNTRIES = 'Nordic Countries',
  NORTHERN_AFRICA = 'Northern Africa',
  BALTIC_COUNTRIES = 'Baltic Countries',
  MELANESIA = 'Melanesia',
  MICRONESIA = 'Micronesia',
  BRITISH_ISLANDS = 'British Islands',
  MICRONESIA_CARIBBEAN = 'Micronesia/Caribbean'
}
